// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package watcher

import (
	"context"
	"github.com/jm199seo/dhg_bot/pkg/discord"
	"github.com/jm199seo/dhg_bot/pkg/loa_api"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func InitializeWatcher(ctx context.Context, cfg *viper.Viper) (*Server, func(), error) {
	config, err := ProvideConfigFromEnvironment(cfg)
	if err != nil {
		return nil, nil, err
	}
	loa_apiConfig, err := loa_api.ProvideConfigFromEnvironment(cfg)
	if err != nil {
		return nil, nil, err
	}
	client := loa_api.NewClient(loa_apiConfig)
	discordConfig, err := discord.ProvideConfigFromEnvironment(cfg)
	if err != nil {
		return nil, nil, err
	}
	discordClient := discord.NewClient(discordConfig)
	server := NewServer(config, client, discordClient)
	return server, func() {
	}, nil
}
