// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package discord

import (
	"context"
	"github.com/jm199seo/dhg_bot/pkg/loa_api"
	"github.com/jm199seo/dhg_bot/pkg/mongo"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func InitializeDiscord(ctx context.Context, cfg *viper.Viper) (*Client, func(), error) {
	config, err := ProvideConfigFromEnvironment(cfg)
	if err != nil {
		return nil, nil, err
	}
	mongoConfig, err := mongo.ProvideConfigFromEnvironment(cfg)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup, err := mongo.NewClient(mongoConfig)
	if err != nil {
		return nil, nil, err
	}
	loa_apiConfig, err := loa_api.ProvideConfigFromEnvironment(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loa_apiClient, err := loa_api.NewClient(loa_apiConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	discordClient, cleanup2, err := NewClient(config, client, loa_apiClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return discordClient, func() {
		cleanup2()
		cleanup()
	}, nil
}
